### ISSUE TITLE
doesn't work behind a proxy 

### ISSUE THREAD

**Issue by eugenio** [yeban/ncbi-blast-dbs#2]
Hi I downloaded and installed correctly but since I'm in a network behind proxy the gem doesn't work.
Is there a way to make it work behind a proxy?

**Comment by yeban** [comment]
I think the part of the code that fetches the list of all databases and its volumes from NCBI's ftp server will have to be modified to work with proxy. Further, the solution will change depending on whether it is HTTP or SOCKS proxy. Unfortunately, I won't be able to implement it because I am not behind a proxy server to be able to test the code. I will be happy to accept a pull-request to address this though. In the meantime you could also look into solutions like [proxychains](http://proxychains.sourceforge.net/) that can make any app work behind any kind of proxy - used to work like a charm when I was in college.

**Comment by sjfranklin** [comment]
I've refactored some code to use HTTP instead of FTP; hopefully this will work for you, @eugenio

**Comment by yeban** [comment]
I have merged @sjfranklin's pull-request. Let us know if that simplifies things.
