### ISSUE TITLE
download from different location

### ISSUE THREAD

**Issue by daveb123** [yeban/ncbi-blast-dbs#3]
Downloading databases from NCBI can be slow and costly even using this program. In Australia they can be downloaded via the AARNET backbone (without charge for academics) and it is much faster. Is there any possibility that an option to define the download location and database (eg: http://biomirror.aarnet.edu.au/biomirror/blast/) could be included?

Thanks

**Comment by yeban** [comment]
That would be very useful. But it's not straightforward to query AARNET for what databases and volumes are available. That's because AARNET uses HTTP, while NCBI uses FTP. Another issue with AARNET is that it doesn't make available md5 checksums of the available files, making it impossible to verify the downloaded file. So I am not sure about it.
